import assert from "node:assert/strict";
import test from "node:test";
import { randomUUID } from "node:crypto";
import { judgeWithJev, type JevChoiceAnswer, type SemanticEvidence, type TypeSafeTransport } from "../src/semantic/jev-boundary.js";
const evidence: SemanticEvidence = { goal: "finish", acceptanceCriteria: ["pass"], executorSummary: "ready", validationResults: ["pass"], blockers: [] };
const env = { TYPESAFE_API_KEY: randomUUID() };
function answer(choice: JevChoiceAnswer["choice"], confidence = .9, selected = .9): JevChoiceAnswer { return { choice, confidence, probabilities: { complete: choice === "complete" ? selected : .05, retry: choice === "retry" ? selected : .05, blocked: choice === "blocked" ? selected : .05 } } }
function mock(value: JevChoiceAnswer, inspect?: TypeSafeTransport): TypeSafeTransport { return async (request, key) => { if (inspect) await inspect(request, key); return { answers: { disposition: value } } } }
test("complete is typed and key stays outside state", async () => { const result = await judgeWithJev(evidence, true, { env, transport: mock(answer("complete"), async (request, key) => { assert.equal(key, env.TYPESAFE_API_KEY); assert.equal(JSON.stringify(request).includes(key), false); return {} }) }); assert.deepEqual(result, { judgment: "complete", probability: .9, confidence: .9, preserveResources: false, reason: "accepted" }) });
test("retry and blocked preserve resources", async () => { for (const choice of ["retry", "blocked"] as const) { const result = await judgeWithJev(evidence, true, { env, transport: mock(answer(choice)) }); assert.equal(result.judgment, choice); assert.equal(result.preserveResources, true) } });
test("exact configured thresholds pass", async () => { const result = await judgeWithJev(evidence, true, { env, thresholds: { minimumConfidence: .8, minimumProbability: .6 }, transport: mock(answer("complete", .8, .6)) }); assert.equal(result.reason, "accepted") });
test("values below either threshold fail safe", async () => { for (const value of [answer("complete", .799, .6), answer("complete", .8, .599)]) { const result = await judgeWithJev(evidence, true, { env, thresholds: { minimumConfidence: .8, minimumProbability: .6 }, transport: mock(value) }); assert.equal(result.reason, "low_confidence"); assert.equal(result.preserveResources, true) } });
test("missing key and API failure fail safe", async () => { let called = false; const missing = await judgeWithJev(evidence, true, { env: {}, transport: async () => { called = true; throw new Error() } }); assert.equal(called, false); assert.equal(missing.reason, "missing_api_key"); const failed = await judgeWithJev(evidence, true, { env, transport: async () => { throw new Error(env.TYPESAFE_API_KEY) } }); assert.equal(failed.reason, "api_failure"); assert.equal(JSON.stringify(failed).includes(env.TYPESAFE_API_KEY), false) });
test("malformed response and invalid threshold fail closed", async () => { const malformed = await judgeWithJev(evidence, true, { env, transport: async () => ({}) }); assert.equal(malformed.reason, "malformed_response"); await assert.rejects(judgeWithJev(evidence, true, { env, thresholds: { minimumConfidence: 2 }, transport: mock(answer("complete")) }), RangeError) });
test("deterministic gate cannot be bypassed", async () => { let called = false; const result = await judgeWithJev(evidence, false, { env, transport: async () => { called = true; return { answers: { disposition: answer("complete") } } } }); assert.equal(called, false); assert.equal(result.reason, "deterministic_gate_failed"); assert.equal(result.judgment, "manual_review") });
test("real TypeSafe smoke is explicitly environment gated", { skip: !process.env.WP_TYPESAFE_REAL_SMOKE || !process.env.TYPESAFE_API_KEY }, async () => { const result = await judgeWithJev(evidence, true); assert.notEqual(result.reason, "missing_api_key"); assert.notEqual(result.reason, "api_failure"); assert.notEqual(result.reason, "malformed_response") });
