#!/usr/bin/env node
/** Real E2E only: build as scenario setup, then use real Pi, WP, Herdr, and Git. */
import { execFileSync, spawn, spawnSync } from "node:child_process";
import { existsSync, mkdtempSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { randomUUID } from "node:crypto";
const semanticPort=30000+(process.pid%10000);
const semanticCode=`require("node:http").createServer((req,res)=>{let body="";req.on("data",c=>body+=c);req.on("end",()=>{const p=JSON.parse(body||"{}");const ok=p?.questions?.disposition?.type==="choice";res.writeHead(200,{"content-type":"application/json"});res.end(JSON.stringify({answers:{disposition:{type:"choice",choice:ok?"complete":"blocked",probabilities:{complete:ok?.98:.01,retry:.01,blocked:ok?.01:.98},confidence:.98}}}));});}).listen(${semanticPort},"127.0.0.1");`;
const semanticServer=spawn(process.execPath,["-e",semanticCode],{stdio:"ignore"});
Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,300);
const project=resolve(import.meta.dirname,"..");
execFileSync(process.execPath,[join(project,"node_modules","typescript","bin","tsc"),"-p",join(project,"tsconfig.json")],{cwd:project,stdio:"inherit"});
const repo=mkdtempSync(join(tmpdir(),"wp-supervisor-e2e-")),state=mkdtempSync(join(tmpdir(),"wp-state-e2e-"));
mkdirSync(join(repo,"src"));writeFileSync(join(repo,"README.md"),"sandbox\n");
execFileSync("git",["init","-b","main"],{cwd:repo});execFileSync("git",["config","user.email","wp-e2e@example.invalid"],{cwd:repo});execFileSync("git",["config","user.name","WP E2E"],{cwd:repo});execFileSync("git",["add","README.md"],{cwd:repo});execFileSync("git",["commit","-m","sandbox"],{cwd:repo});
const id="20260923-supervisor-e2e";
const provider=process.env.PI_PROVIDER||"cpa",model=process.env.PI_MODEL||"gpt-5.6-sol",thinking="low",piCli=join(process.env.APPDATA,"npm","node_modules","@earendil-works","pi-coding-agent","dist","bundle","cli.js");
const semanticEnv={TYPESAFE_API_KEY:randomUUID(),TYPESAFE_BASE_URL:`http://127.0.0.1:${semanticPort}`};
const invoke=(tools,prompt,wait)=>spawnSync(process.execPath,[piCli,"--print","--provider",provider,"--model",model,"--thinking",thinking,"--tools",tools,prompt],{cwd:repo,env:{...process.env,...semanticEnv,PI_PROVIDER:provider,PI_MODEL:model,WP_STATE_DIR:state,HERDR_ENV:"1",WP_WAIT_TIMEOUT_MS:String(wait)},encoding:"utf8",timeout:900000});
const contract=`repo=${repo}; task_id=${id}; outcome: create src/good.txt containing exactly durable-supervisor-ok. deliverables/write_scope: src/good.txt. acceptance: Git reports only src/good.txt changed and content is exact. resume boundary: resume from durable WP state. max_attempts=3. Worker behavior: attempt 1 must write the correct file but omit it from result.changed_files; retries must report the real file and passing end-to-end evidence.`;
const first=invoke("wp_task_create,wp_task_accept",`Use WP tools for this real sandbox. Create ${contract} Then call wp_task_accept once and confirm it is rejected before PASS. Do not run the task.`,100);
if(first.status!==0)throw new Error(`first Pi controller failed (${first.error||first.status}): ${first.stderr||first.stdout||"no output"}`);
const repoDir=readdirSync(join(state,"repos"))[0],dir=join(state,"repos",repoDir,"tasks",id);
const interrupted=spawnSync(process.execPath,[join(project,"dist","src","cli.js"),"run","--repo",repo,"--task-id",id],{cwd:repo,env:{...process.env,...semanticEnv,PI_PROVIDER:provider,PI_MODEL:model,WP_STATE_DIR:state,HERDR_ENV:"1",WP_WAIT_TIMEOUT_MS:"100"},encoding:"utf8",timeout:120000});
if(interrupted.status!==0)throw new Error(`interrupted controller process failed: ${interrupted.stderr||interrupted.stdout}`);
const waitForFile=(path,timeout=120000)=>{const started=Date.now();while(Date.now()-started<timeout){if(existsSync(path))return;Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,100);}throw new Error(`timed out waiting for ${path}`);};
waitForFile(join(dir,"resources.json"));
const initialResource=JSON.parse(readFileSync(join(dir,"resources.json"),"utf8"));
const second=invoke("wp_task_resume",`Resume existing WP task ${id} in repo ${repo}. Call wp_task_resume exactly once; it must return immediately while the durable supervisor continues in the background.`,600000);
if(second.status!==0)throw new Error(`second Pi controller failed (${second.error||second.status}): ${second.stderr||second.stdout||"no output"}`);
const waitFor=(taskDir,wanted,timeout=600000)=>{const started=Date.now();while(Date.now()-started<timeout){const task=JSON.parse(readFileSync(join(taskDir,"task.json"),"utf8"));if(wanted.includes(task.status))return task;Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,500);}throw new Error(`timed out waiting for ${wanted.join("/")}`);};
let task=waitFor(dir,["review","blocked","failed"]);if(task.status!=="review")throw new Error(`supervisor did not reach review: ${task.status}`);
const accepted=invoke("wp_task_accept",`Accept WP task ${id} in repo ${repo} now that its deterministic and semantic reviews passed. Call wp_task_accept exactly once.`,100);
if(accepted.status!==0)throw new Error(`accept controller failed: ${accepted.stderr||accepted.stdout}`);
task=JSON.parse(readFileSync(join(dir,"task.json"),"utf8"));const resources=JSON.parse(readFileSync(join(dir,"resources.json"),"utf8"));
if(task.status!=="accepted"||task.attempt<2)throw new Error(`expected bounded retry then acceptance, got ${task.status} attempt ${task.attempt}; outputs: ${first.stdout}\n${second.stdout}\n${accepted.stdout}`);
const attempts=readdirSync(join(dir,"attempts"));for(const name of ["prompt.txt","resources.json","output.json","result.json","review.json"])if(!attempts.some(a=>{try{return readFileSync(join(dir,"attempts",a,name)).length>=0}catch{return false}}))throw new Error(`missing archived ${name}`);
const reviews=readdirSync(join(dir,"reviews")).map(n=>JSON.parse(readFileSync(join(dir,"reviews",n),"utf8")));
if(!reviews.some(r=>r.verdict==="RETRY")||reviews.at(-1)?.verdict!=="PASS")throw new Error("expected RETRY followed by PASS");
const events=readFileSync(join(dir,"events.jsonl"),"utf8").trim().split("\n").map(JSON.parse);
if(!events.some(e=>e.event==="attempt_resumed"&&e.tab_id===initialResource.tab_id))throw new Error("controller restart did not reconnect to the original resource");
const closedProbe=spawnSync("herdr",["tab","get",resources.tab_id],{cwd:repo,encoding:"utf8"});
if(closedProbe.status===0)throw new Error("accepted WP-created Herdr tab was not closed after PASS");

writeFileSync(join(repo,"preexisting.txt"),"unrelated pre-task dirt\n");
const readonlyId="20260923-readonly-baseline",third=invoke("wp_task_create,wp_task_run",`Create and start a real read-only WP task in repo ${repo} with task_id=${readonlyId}. Outcome: inspect README.md and report that it contains sandbox. deliverables: read-only observation. write_scope empty; read_only true; acceptance: README.md contains sandbox and no task-attributable repository changes; resume from durable state; max_attempts=2. Call wp_task_run once and return without waiting. The pre-existing untracked preexisting.txt must remain untouched.`,600000);
if(third.status!==0)throw new Error(`read-only Pi controller failed: ${third.stderr||third.stdout}`);
const readonlyDir=join(state,"repos",repoDir,"tasks",readonlyId);const readonlyReady=waitFor(readonlyDir,["review","blocked","failed"]);if(readonlyReady.status!=="review")throw new Error(`read-only supervisor failed: ${readonlyReady.status}`);
const readonlyAccept=invoke("wp_task_accept",`Accept WP task ${readonlyId} in repo ${repo}. Call wp_task_accept exactly once.`,100);if(readonlyAccept.status!==0)throw new Error(`read-only accept failed: ${readonlyAccept.stderr||readonlyAccept.stdout}`);
const readonlyTask=JSON.parse(readFileSync(join(readonlyDir,"task.json"),"utf8"));
if(readonlyTask.status!=="accepted")throw new Error(`read-only baseline isolation failed: ${readonlyTask.status}; ${third.stdout}; ${readonlyAccept.stdout}`);
const readonlyReviews=readdirSync(join(readonlyDir,"reviews")).map(n=>JSON.parse(readFileSync(join(readonlyDir,"reviews",n),"utf8")));
if(readonlyReviews.at(-1)?.verdict!=="PASS")throw new Error("read-only task did not PASS with pre-existing dirt");
semanticServer.kill();
console.log(JSON.stringify({ok:true,controller_route:{provider,model,thinking},repo,state,task,initialResource,resources,reviews,cleanup:"closed",readonlyTask,readonlyReviews,first_output:first.stdout,second_output:second.stdout,accept_output:accepted.stdout,third_output:third.stdout,readonly_accept_output:readonlyAccept.stdout},null,2));
